services:

    postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: app
        POSTGRES_USER: app
        POSTGRES_DB: transaction
      ports:
        - "5432:5432"

