spring.ai.openai.api-key=${OpenAi_Key}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.ai.model.audio.transcription=openai
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.prompt=Audio em pt-br \
  Audio contem descrição dos gastos \
  As frases geralmente contem: \
  - um valor em reais (numero + "reais") \
  - uma ação (gastei, paguei, comprei) \
  - um local ou estabelecimento (mercado, farmacia, restaurante, loja, etc.)


spring.ai.model.audio.speech=openai
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.voice=onyx
spring.ai.openai.audio.speech.options.speed=1.3
spring.ai.openai.audio.speech.options.response-format=mp3




logging.level.org.springframework.ai=DEBUG